// <auto-generated />
using System;
using AcademicDevP.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicDev.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicDev.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "C++"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "C#"
                        });
                });

            modelBuilder.Entity("AcademicDev.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfPublish")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GithubLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrjName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CategoryId = 1,
                            DateOfPublish = new DateTime(2024, 1, 18, 20, 42, 58, 59, DateTimeKind.Utc).AddTicks(3956),
                            Description = "Real-time chat application",
                            GithubLink = "https://github.com/yourusername/ChatApp",
                            Image = "chatapp.jpg",
                            PrjName = "ChatApp"
                        },
                        new
                        {
                            ProjectId = 2,
                            CategoryId = 2,
                            DateOfPublish = new DateTime(2024, 1, 18, 20, 42, 58, 59, DateTimeKind.Utc).AddTicks(3960),
                            Description = "Simple task management system",
                            GithubLink = "https://github.com/yourusername/TaskManager",
                            Image = "taskmanager.png",
                            PrjName = "TaskManager"
                        },
                        new
                        {
                            ProjectId = 3,
                            CategoryId = 1,
                            DateOfPublish = new DateTime(2024, 1, 18, 20, 42, 58, 59, DateTimeKind.Utc).AddTicks(3962),
                            Description = "Online e-commerce platform",
                            GithubLink = "https://github.com/yourusername/ECommerceSite",
                            Image = "ecommercesite.jpg",
                            PrjName = "ECommerceSite"
                        });
                });

            modelBuilder.Entity("AcademicDev.Models.Project", b =>
                {
                    b.HasOne("AcademicDev.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
